database:
    db:   tennis
    user: tennis
    pwd:  tennis
    host: localhost
    port: 5432

# Configuration for logging
log:
    slack:
        api_key: xoxb-280090289303-njD9i7HXqkuBUanGiT7LetuH
        channel: '#surebot'
    